import {Platform} from 'react-native';

const HORIZONTAL_SPACING_BASE = Platform.OS === 'web' ? 4 : 2;
const VERTICAL_SPACING_BASE = 4;

const icons = {
  logo: require('../assets/icons/rocket-icon.png'),
  delayedLogo: require('../assets/icons/rocket-icon.png'),
  firebase: require('../assets/icons/firebase-icon.png'),
  userAvatar: require('../assets/icons/default-avatar.jpg'),
  userDefault: require('../assets/icons/userDefault.png'),
  backArrow: require('../assets/icons/arrow-back-icon.png'),
  chevron_right: require('../assets/icons/chevron-right.png'),
  add: require('../assets/icons/add.png'),
  home_android: require('../assets/icons/home-icon-24.png'),
  search: require('../assets/icons/search.png'),
  camera: require('../assets/icons/camera.png'),
  cameraFilled: require('../assets/icons/camera-filled.png'),
  inscription: require('../assets/icons/inscription.png'),
  pinpoint: require('../assets/icons/pinpoint.png'),
  pinpoint_fat: require('../assets/icons/pinpoint-fat.png'),
  calendar_clock : require('../assets/icons/calendar-clock.png'),
  list_circle : require('../assets/icons/list-circle.png'),
  checked: require('../assets/icons/checked.png'),
  bell: require('../assets/icons/bell.png'),
  logout: require('../assets/icons/logout-drawer.png'),
  users_android: require('../assets/icons/users-icon-48.png'),
  users_more: require('../assets/icons/users-more.png'),
  user_plus: require('../assets/icons/user-plus.png'),
  user_android: require('../assets/icons/account-detail.png'),
  warning_circle: require('../assets/icons/warning-circle.png'),
  heart: require('../assets/icons/heart.png'),
  heart_gray : require('../assets/icons/heart-gray.png'),
  comment: require('../assets/icons/comment.png'),
  link: require('../assets/icons/link.png'),
  xedayhang: require('../assets/icons/xedayhang.png'),
  bookmark: require('../assets/icons/bookmark.png'),
  message_square_dots: require('../assets/icons/message-square-dots.png'),
  login: require('../assets/icons/login.png'),
  trash_2: require('../assets/icons/trash-2.png'),
};

const lightColors = {
  primaryBackground: '#ffffff',
  secondaryBackground: '#F5F5F5',
  thirBackground: '#0F3D4B',
  forthBackground: '#414446',
  fifthBackground: '#B65A46',
  sixthBackground: '#EBC5CC',
  componentBackground: '#FFEAC5',
  componentBackground2: '#FFDBB5',
  primaryForeground: '#5244F3',
  secondaryForeground: '#8442bd',
  foregroundContrast: 'white',
  primaryText: '#151723',
  secondaryText: '#7e7e7e',
  thirText: '#4FC98F',
  fourthText: '#615ECF',
  hairline: '#e0e0e0',
  grey0: '#fafafa',
  grey3: '#f5f5f5',
  grey6: '#d6d6d6',
  grey9: '#939393',
  grey12: '#808080',
  red: '#ea0606',
  blue: '#177AD5',
  primaryButtonTabNonActive: '#000000',
  primaryButtonTabActive: '#0F3D4B',
  primaryButtonTextNonActive: 'rgba(0, 0, 0, 0.5)',
  primaryBorder: '#000000',
  svgColor: '#000',
  alertColor: '#F7CECD',
  warningColor: '#8F4D1A',
  disabledText: '#A0A0A0',
};

const MobileTheme = {
  colors: {
    light: lightColors,
    'no-preference': lightColors,
    dark: {
      primaryBackground: '#1A1A1A',
      secondaryBackground: '#000000',
      thirBackground: '#E5F554',
      forthBackground: '#414446',
      fifthBackground: '#B65A46',
      sixthBackground: '#EBC5CC',
      componentBackground: '#141433',
      componentBackground2: '#3E493E',
      primaryForeground: '#5244F3',
      secondaryForeground: '#8442bd',
      foregroundContrast: 'white',
      primaryText: '#ffffff',
      secondaryText: '#c5c5c5',
      thirText: '#4FC98F',
      fourthText: '#615ECF',
      hairline: '#222222',
      grey0: '#0a0a0a',
      grey3: '#2a2a2a',
      grey6: '#f5f5f5',
      grey9: '#eaeaea',
      grey12: '#808080',
      red: '#ea0606',
      blue: '#177AD5',
      primaryButtonTabActive: '#5244F3',
      primaryButtonTabNonActive: '#EEE4FF',
      primaryButtonTextNonActive: 'rgba(238, 228, 255, 0.5)',
      primaryBorder: '#5244F3',
      svgColor: '#fff',
      alertColor: '#F7CECD',
      warningColor: '#8F4D1A',
      disabledText: '#505050',
    },
  },
  spaces: {
    horizontal: {
      s: 2 * HORIZONTAL_SPACING_BASE,
      m: 4 * HORIZONTAL_SPACING_BASE,
      l: 6 * HORIZONTAL_SPACING_BASE,
      xl: 8 * HORIZONTAL_SPACING_BASE,
    },
    vertical: {
      s: 2 * VERTICAL_SPACING_BASE,
      m: 4 * VERTICAL_SPACING_BASE,
      l: 6 * VERTICAL_SPACING_BASE,
      xl: 8 * VERTICAL_SPACING_BASE,
    },
  },
  fontSizes: {
    xxs: 8,
    xs: 12,
    s: 14,
    m: 16,
    l: 18,
    xl: 24,
    xxl: 32,
  },
  fontWeights: {
    s: '400',
    m: '600',
    l: '800',
  },
  icons: icons,
  // color, font size, space / margin / padding, vstack / hstack
  button: {
    borderRadius: 8,
  },
};

export default MobileTheme;
